#
# MM30 Feature-phenotype association pipeline config
#
name: 'mm30'
version: '6.0'

# number of permuted versions of the data to use for generating null distributions
num_permutations: 1000

output_dir: '/data/proj/mm30/6.0/fassoc'
